before_script:
  - . ~/.nvm/nvm.sh
  - nvm use 8.9.4
  - npm install -g forever

cache:
  paths:
    - node_modules/

stages:
  - test
  - deploy

lintear:
  stage: test
  script:
    - npm install
    - npm run lint

deploy_desarrollo:
  stage: deploy
  script:
    - npm install
    - npm run build
    - rsync -rlDv --delete * /software/trakapp/backend/
    - exec() { NODE_ENV=$NODE_ENV PUERTO=$PUERTO ORIGIN=$ORIGIN MONGO_URI=$MONGO_URI `forever stop trakapp 2>/dev/null || :` && `forever start --append --uid trakapp /software/base/backend/dist`  }
  environment:
    name: desarrollo
    url: trackapp.ciriscr.com:7001
  only:
  - desarrollo
