before_script:
  - . ~/.nvm/nvm.sh
  - nvm use 8.9.4
  - npm install -g forever

stages:
  - test
  - deploy

lintear:
  stage: test
  script:
    - npm install
    - npm run lint

deploy_desarrollo:
  stage: deploy
  script:
    - npm install
    - npm run build
    - rsync -rlDv --delete * /software/trakapp/pruebas/backend/
    - "forever stop trakapp-staging 2>/dev/null || :"
    - NODE_ENV=$MODO_ST DEBUG=$DEBUG PUERTO=$PUERTO_ST ORIGIN=$ORIGIN_ST MONGO_URI=$MONGO_URI_ST ADMIN_URL=$ADMIN_URL_ST MAILGUN_DOMAIN=$MAILGUN_DOMAIN_ST forever start --append --uid trakapp-staging /software/trakapp/pruebas/backend/dist
  environment:
    name: desarrollo
    url: trackapp.ciriscr.com:7001
  only:
  - desarrollo

deploy_estable:
  stage: deploy
  script:
    - npm install
    - npm run build
    - rsync -rlDv --delete * /software/trakapp/produccion/backend
    - "forever stop trakapp-produccion 2>/dev/null || :"
    - NODE_ENV=$MODO_PR DEBUG=$DEBUG PUERTO=$PUERTO_PR ORIGIN=$ORIGIN_PR MONGO_URI=$MONGO_URI_PR ADMIN_URL=$ADMIN_URL_PR MAILGUN_DOMAIN=$MAILGUN_DOMAIN_PR forever start --append --uid trakapp-produccion /software/trakapp/produccion/backend/dist
  environment:
    name: estable
    url: backend.trakapp.co.cr
  only:
  - estable
